# Generated by Django 4.2.9 on 2024-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Parametros',
                'ordering': ('nombre',),
            },
        ),
    ]
