# Generated by Django 4.2.9 on 2024-01-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=255)),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField()),
            ],
        ),
    ]
