# Generated by Django 4.2.9 on 2024-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ('hora_ingreso',), 'verbose_name_plural': 'Registros'},
        ),
        migrations.AddField(
            model_name='registro',
            name='pago_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
