# Generated by Django 4.2.9 on 2024-01-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_parametro_alter_registro_options_registro_pago_total_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametro',
        ),
    ]
